### ISSUE TITLE
markdown

### ISSUE THREAD

**Issue by brianamarie** [githubteacher/git-nov-3#2]
https://guides.github.com/features/mastering-markdown/

**Comment by brianamarie** [comment]
Info for adding branch name to bash is in the readme of [this repository](https://github.com/githubteacher/developers-november-2016).

**Comment by brianamarie** [comment]
Questions

- If I do 'git config --local', where is that info actually stored? 
- How can I search through commit messages? 
- Let's do more with `stash`, `pop`, and `apply`

**Comment by 4amal** [comment]
Amal

**Comment by githubteacher** [comment]
Why would `git checkout -b origin/stats-update` work for some and not others?

**Comment by brianamarie** [comment]
> If I do 'git config --local', where is that info actually stored?

That's stored in the local .git folder, but isn't pushed up with the rest of the .git information. Via [git-scm](https://git-scm.com/docs/git-push), a push only sends what's necessary. "Updates remote refs using local refs, while sending objects necessary to complete the given refs." 

> How can I search through commit messages?

`git log --grep=something`

**Comment by brianamarie** [comment]
> Let's do more with stash, pop, and apply

[Good resource in case we don't have time to cover it tomorrow](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history)

**Comment by brianamarie** [comment]
https://docs.google.com/presentation/d/1cZKMG-XFU7b14KyEj-9rrOKW4NwMw0u33svfh3Vd2fs/edit?usp=sharing

**Comment by githubteacher** [comment]
brianamarie@github.com 

services@github.com
